export const GET_BIRDS_BEGIN = 'GET_BIRDS_BEGIN';
export const GET_BIRDS_SUCCESS = 'GET_BIRDS_SUCCESS';
export const GET_BIRDS_FAIL = 'GET_BIRDS_FAIL';
export const FILTER_SEARCH_QUERY = 'FILTER_SEARCH_QUERY';
export const INFO_CLICKED_BEGIN = 'INFO_CLICKED_BEGIN';
export const INFO_CLICKED_SUCCESS = 'INFO_CLICKED_SUCCESS';
export const INFO_CLICKED_FAIL = 'INFO_CLICKED_FAIL';
